const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.Tween,
		C3.Plugins.Text,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Behaviors.Tween.Acts.TweenValue,
		C3.Behaviors.Tween.Acts.TweenTwoProperties,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Behaviors.Tween.Acts.TweenOneProperty,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.System.Exps.max,
		C3.Behaviors.Tween.Cnds.OnTweensFinished,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Sprite.Acts.MoveToTop,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.System.Exps.random,
		C3.Plugins.Text.Acts.SetVisible,
		C3.Plugins.Text.Acts.SetPos,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.System.Acts.SetVar,
		C3.Behaviors.Tween.Cnds.IsPlaying,
		C3.Plugins.Sprite.Acts.SetEffectParam,
		C3.Behaviors.Tween.Exps.Value
	];
};
self.C3_JsPropNameTable = [
	{Strength: 0},
	{Vitality: 0},
	{Agility: 0},
	{Speed: 0},
	{Defense: 0},
	{MaxHealth: 0},
	{HealthRegen: 0},
	{PhysicalDamage: 0},
	{AttackSpeed: 0},
	{DodgeChance: 0},
	{MovementSpeed: 0},
	{CriticalDamage: 0},
	{CriticalChance: 0},
	{DamageReduction: 0},
	{FinalDamage: 0},
	{FinalDamageTaken: 0},
	{Tween: 0},
	{PlayerCombat: 0},
	{enemyID: 0},
	{hitpoints: 0},
	{attack: 0},
	{posX: 0},
	{posY: 0},
	{EnemyCombat: 0},
	{UICombatBG: 0},
	{EnemyHealth: 0},
	{PlayerHealth: 0},
	{Damage: 0},
	{DebugStatsPlayer: 0},
	{DebugStatsEnemy: 0},
	{Debug: 0},
	{Family1: 0},
	{RandomChoice: 0},
	{character: 0}
];

self.InstanceType = {
	PlayerCombat: class extends self.ISpriteInstance {},
	EnemyCombat: class extends self.ISpriteInstance {},
	UICombatBG: class extends self.ISpriteInstance {},
	EnemyHealth: class extends self.ITextInstance {},
	PlayerHealth: class extends self.ITextInstance {},
	Damage: class extends self.ITextInstance {},
	DebugStatsPlayer: class extends self.ITextInstance {},
	DebugStatsEnemy: class extends self.ITextInstance {},
	Debug: class extends self.ITextInstance {},
	Family1: class extends self.ISpriteInstance {}
}